name: Update bilibili latest vids

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "10 * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Deno"
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 2c80d725b0378168e3e43c9459b0e8cd
          UID: '3596837'
        run: deno run --allow-net --allow-env index.ts
